import 'package:get/get_navigation/src/root/internacionalization.dart';

class Mylocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar': {
          '1': 'الوضع الليلي',
          '2': 'الوضع النهاري',
          '3': "فن",
          '4': "تاريخ",
          '5':'برمجة',  
          '6':'علوم',
          '7':'الرئيسية',
          '8':'بحث',
          '9':'المفضلة',
          '10':'الملف الشخصي',
          '11':'المظهر',
          '12':'مفعل',
          '13':'مغلق',
          '14':'اللغة',
          '15':'الحساب',
          '16':'البريد الإلكتروني موثق',
          '17':'تم التحقق',
          '18':'لم يتم التحقق',
          '19':'تسجيل الخروج',
          '20':'البحث عن الكتب، المؤلفين، الناشرين',
          '21':'لا يوجد سجل بحث',
          '22':'سيظهر سجل البحث الحديث هنا',
          '23':'البحث الحديث',
          '24':'مسح الكل',
          '25':'مميز',
          '26':'استكشف ',
          '27':'الوصف',
          '28':'المؤلف',
          '29':'غير معروف',
          '30':'الناشر',
          '31':'كتب مشابهة',
          '32':'أراك في المرة القادمة',
          '33':'عرض الجميع',
          '34':'لا توجد كتب محفوظة بعد',
          '35':'اضغط على ★ على أي كتاب لحفظه هنا',
          '36':'اقرأ مقتطفاً',
          '37':'مقتطفاً',
          '38':'مدفوع',
          '39':'غير متاح للقراءة المجانية',
          '40':'عرض في Google Books',
          '41':'لا يوجد وصف متاح لهذا الكتاب.',
          '42':'لم يتم العثور على كتب مشابهة.',
          '43':'مؤلف غير معروف',
          '44':'مجاني',
          '45':'غير متاح للقراءة المجانية',
          '46':'ابحث عن نسخة مجانية',
          '47':'افتح في Google Books',
          '48':'هذا الكتاب محمي بحقوق النشر ولا يمكن قراءته مجاناً.\n'
              'ولكن يمكنك البحث عن نسخة مجانية أو شرائه من Google Books.',
          '49':'فشل تحميل الكتاب',
          '50':'إعادة المحاولة',
          '51':'افتح في المتصفح',

          


         
        },
        'en': {
          '1': 'Dark Mode',
          '2': 'Light Mode',
          '3': "Art",
          '4': "History",
          '5':'Programming',
          '6':'Science',
          '7':'Home',
          '8':'search', 
          '9':'My Favorites',
          '10':'My Profile',
          '11':'appearance',
          '12':'On',
          '13':'Off',
          '14':'Language',
          '15':'Account',
          '16':'Email Verified',
          '17':'Verified',
          '18':'Not verified',
          '19':'Sign Out',
          '20':'Search for books, authors, publishers',
          '21':'No search history',
          '22':'Your recent searches will appear here',
          '23':'RECENT SEARCHES',
          '24':'Clear all',
          '25':'FEATURED',
          '26':'Explore',
          '27':'Description',
          '28':'Author',
          '29':'Unknown',
          '30':'Publisher',
          '31':'Similar Books',
          '32':'See you next time',
          '33':'See all',
          '34':'No saved books yet',
          '35':'Tap the ★ on any book to save it here',
          '36':'Read a preview',
          '37':'preview',
          '38':'Paid',
          '39':'Not Available for Free Reading',
          '40':'View on Google Books',
          '41':'No description available for this book.',
          '42':'No similar books found.',
          '43':'Unknown Author',
          '44':'free',
          '45':'Not Available for Free Reading',
          '46':'Search for a free version',
          '47':'Open in Google Books',
          '48':'This book is protected by copyright and cannot be read for free.\n'
              'But you can search for a free version or purchase it from Google Books.',
          '49':'Failed to load the book',
          '50':'Retry',
          '51':'Open in Browser',
    
          
        },
      };
} 